version: "3.1"
services:
    web:
      image: php:7.3-apache
      container_name: php
      ports:
        - "80:80"
      volumes:
        - .:/var/www/html
    db:
        image: mysql:8.0
        platform: linux/amd64
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: dbname
            MYSQL_USER: root
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
volumes:
    persistent:
